// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	biz "userMicros/internal/biz"

	mock "github.com/stretchr/testify/mock"
)

// UserRepo is an autogenerated mock type for the UserRepo type
type UserRepo struct {
	mock.Mock
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *UserRepo) FindByID(ctx context.Context, id int64) (*biz.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *biz.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*biz.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *biz.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*biz.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserStarRecord provides a mock function with given fields: ctx, userId, etfId
func (_m *UserRepo) UserStarRecord(ctx context.Context, userId int64, etfId int64) error {
	ret := _m.Called(ctx, userId, etfId)

	if len(ret) == 0 {
		panic("no return value specified for UserStarRecord")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, userId, etfId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserRepo creates a new instance of UserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepo {
	mock := &UserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
